// Trampolines auto-générés pour vk*, D3D11*, D3D12*

void* g_pfn_D3D11CreateDevice = nullptr;
void* g_pfn_D3D11CreateDeviceAndSwapChain = nullptr;
void* g_pfn_D3D12CreateRootSignatureDeserializer = nullptr;
void* g_pfn_D3D12CreateVersionedRootSignatureDeserializer = nullptr;
void* g_pfn_D3D12EnableExperimentalFeatures = nullptr;
void* g_pfn_D3D12GetDebugInterface = nullptr;
void* g_pfn_D3D12GetInterface = nullptr;
void* g_pfn_D3D12SerializeRootSignature = nullptr;
void* g_pfn_D3D12SerializeVersionedRootSignature = nullptr;
void* g_pfn_vkAcquireNextImageKHR = nullptr;
void* g_pfn_vkAllocateCommandBuffers = nullptr;
void* g_pfn_vkAllocateDescriptorSets = nullptr;
void* g_pfn_vkAllocateMemory = nullptr;
void* g_pfn_vkBeginCommandBuffer = nullptr;
void* g_pfn_vkBindBufferMemory = nullptr;
void* g_pfn_vkBindBufferMemory2 = nullptr;
void* g_pfn_vkBindImageMemory = nullptr;
void* g_pfn_vkBindImageMemory2 = nullptr;
void* g_pfn_vkCmdBeginQuery = nullptr;
void* g_pfn_vkCmdBeginRenderPass = nullptr;
void* g_pfn_vkCmdBeginRenderPass2 = nullptr;
void* g_pfn_vkCmdBeginRendering = nullptr;
void* g_pfn_vkCmdBindDescriptorSets = nullptr;
void* g_pfn_vkCmdBindIndexBuffer = nullptr;
void* g_pfn_vkCmdBindPipeline = nullptr;
void* g_pfn_vkCmdBindVertexBuffers = nullptr;
void* g_pfn_vkCmdBindVertexBuffers2 = nullptr;
void* g_pfn_vkCmdBlitImage = nullptr;
void* g_pfn_vkCmdBlitImage2 = nullptr;
void* g_pfn_vkCmdClearAttachments = nullptr;
void* g_pfn_vkCmdClearColorImage = nullptr;
void* g_pfn_vkCmdClearDepthStencilImage = nullptr;
void* g_pfn_vkCmdCopyBuffer = nullptr;
void* g_pfn_vkCmdCopyBuffer2 = nullptr;
void* g_pfn_vkCmdCopyBufferToImage = nullptr;
void* g_pfn_vkCmdCopyBufferToImage2 = nullptr;
void* g_pfn_vkCmdCopyImage = nullptr;
void* g_pfn_vkCmdCopyImage2 = nullptr;
void* g_pfn_vkCmdCopyImageToBuffer = nullptr;
void* g_pfn_vkCmdCopyImageToBuffer2 = nullptr;
void* g_pfn_vkCmdCopyQueryPoolResults = nullptr;
void* g_pfn_vkCmdDispatch = nullptr;
void* g_pfn_vkCmdDispatchBase = nullptr;
void* g_pfn_vkCmdDispatchIndirect = nullptr;
void* g_pfn_vkCmdDraw = nullptr;
void* g_pfn_vkCmdDrawIndexed = nullptr;
void* g_pfn_vkCmdDrawIndexedIndirect = nullptr;
void* g_pfn_vkCmdDrawIndexedIndirectCount = nullptr;
void* g_pfn_vkCmdDrawIndirect = nullptr;
void* g_pfn_vkCmdDrawIndirectCount = nullptr;
void* g_pfn_vkCmdEndQuery = nullptr;
void* g_pfn_vkCmdEndRenderPass = nullptr;
void* g_pfn_vkCmdEndRenderPass2 = nullptr;
void* g_pfn_vkCmdEndRendering = nullptr;
void* g_pfn_vkCmdExecuteCommands = nullptr;
void* g_pfn_vkCmdFillBuffer = nullptr;
void* g_pfn_vkCmdNextSubpass = nullptr;
void* g_pfn_vkCmdNextSubpass2 = nullptr;
void* g_pfn_vkCmdPipelineBarrier = nullptr;
void* g_pfn_vkCmdPipelineBarrier2 = nullptr;
void* g_pfn_vkCmdPushConstants = nullptr;
void* g_pfn_vkCmdResetEvent = nullptr;
void* g_pfn_vkCmdResetEvent2 = nullptr;
void* g_pfn_vkCmdResetQueryPool = nullptr;
void* g_pfn_vkCmdResolveImage = nullptr;
void* g_pfn_vkCmdResolveImage2 = nullptr;
void* g_pfn_vkCmdSetBlendConstants = nullptr;
void* g_pfn_vkCmdSetCullMode = nullptr;
void* g_pfn_vkCmdSetDepthBias = nullptr;
void* g_pfn_vkCmdSetDepthBiasEnable = nullptr;
void* g_pfn_vkCmdSetDepthBounds = nullptr;
void* g_pfn_vkCmdSetDepthBoundsTestEnable = nullptr;
void* g_pfn_vkCmdSetDepthCompareOp = nullptr;
void* g_pfn_vkCmdSetDepthTestEnable = nullptr;
void* g_pfn_vkCmdSetDepthWriteEnable = nullptr;
void* g_pfn_vkCmdSetDeviceMask = nullptr;
void* g_pfn_vkCmdSetEvent = nullptr;
void* g_pfn_vkCmdSetEvent2 = nullptr;
void* g_pfn_vkCmdSetFrontFace = nullptr;
void* g_pfn_vkCmdSetLineWidth = nullptr;
void* g_pfn_vkCmdSetPrimitiveRestartEnable = nullptr;
void* g_pfn_vkCmdSetPrimitiveTopology = nullptr;
void* g_pfn_vkCmdSetRasterizerDiscardEnable = nullptr;
void* g_pfn_vkCmdSetScissor = nullptr;
void* g_pfn_vkCmdSetScissorWithCount = nullptr;
void* g_pfn_vkCmdSetStencilCompareMask = nullptr;
void* g_pfn_vkCmdSetStencilOp = nullptr;
void* g_pfn_vkCmdSetStencilReference = nullptr;
void* g_pfn_vkCmdSetStencilTestEnable = nullptr;
void* g_pfn_vkCmdSetStencilWriteMask = nullptr;
void* g_pfn_vkCmdSetViewport = nullptr;
void* g_pfn_vkCmdSetViewportWithCount = nullptr;
void* g_pfn_vkCmdUpdateBuffer = nullptr;
void* g_pfn_vkCmdWaitEvents = nullptr;
void* g_pfn_vkCmdWaitEvents2 = nullptr;
void* g_pfn_vkCmdWriteTimestamp = nullptr;
void* g_pfn_vkCmdWriteTimestamp2 = nullptr;
void* g_pfn_vkCreateBuffer = nullptr;
void* g_pfn_vkCreateBufferView = nullptr;
void* g_pfn_vkCreateCommandPool = nullptr;
void* g_pfn_vkCreateComputePipelines = nullptr;
void* g_pfn_vkCreateDescriptorPool = nullptr;
void* g_pfn_vkCreateDescriptorSetLayout = nullptr;
void* g_pfn_vkCreateDescriptorUpdateTemplate = nullptr;
void* g_pfn_vkCreateDevice = nullptr;
void* g_pfn_vkCreateEvent = nullptr;
void* g_pfn_vkCreateFence = nullptr;
void* g_pfn_vkCreateFramebuffer = nullptr;
void* g_pfn_vkCreateGraphicsPipelines = nullptr;
void* g_pfn_vkCreateImage = nullptr;
void* g_pfn_vkCreateImageView = nullptr;
void* g_pfn_vkCreateInstance = nullptr;
void* g_pfn_vkCreatePipelineCache = nullptr;
void* g_pfn_vkCreatePipelineLayout = nullptr;
void* g_pfn_vkCreatePrivateDataSlot = nullptr;
void* g_pfn_vkCreateQueryPool = nullptr;
void* g_pfn_vkCreateRenderPass = nullptr;
void* g_pfn_vkCreateRenderPass2 = nullptr;
void* g_pfn_vkCreateSampler = nullptr;
void* g_pfn_vkCreateSamplerYcbcrConversion = nullptr;
void* g_pfn_vkCreateSemaphore = nullptr;
void* g_pfn_vkCreateShaderModule = nullptr;
void* g_pfn_vkCreateSwapchainKHR = nullptr;
void* g_pfn_vkCreateWin32SurfaceKHR = nullptr;
void* g_pfn_vkDestroyBuffer = nullptr;
void* g_pfn_vkDestroyBufferView = nullptr;
void* g_pfn_vkDestroyCommandPool = nullptr;
void* g_pfn_vkDestroyDescriptorPool = nullptr;
void* g_pfn_vkDestroyDescriptorSetLayout = nullptr;
void* g_pfn_vkDestroyDescriptorUpdateTemplate = nullptr;
void* g_pfn_vkDestroyDevice = nullptr;
void* g_pfn_vkDestroyEvent = nullptr;
void* g_pfn_vkDestroyFence = nullptr;
void* g_pfn_vkDestroyFramebuffer = nullptr;
void* g_pfn_vkDestroyImage = nullptr;
void* g_pfn_vkDestroyImageView = nullptr;
void* g_pfn_vkDestroyInstance = nullptr;
void* g_pfn_vkDestroyPipeline = nullptr;
void* g_pfn_vkDestroyPipelineCache = nullptr;
void* g_pfn_vkDestroyPipelineLayout = nullptr;
void* g_pfn_vkDestroyPrivateDataSlot = nullptr;
void* g_pfn_vkDestroyQueryPool = nullptr;
void* g_pfn_vkDestroyRenderPass = nullptr;
void* g_pfn_vkDestroySampler = nullptr;
void* g_pfn_vkDestroySamplerYcbcrConversion = nullptr;
void* g_pfn_vkDestroySemaphore = nullptr;
void* g_pfn_vkDestroyShaderModule = nullptr;
void* g_pfn_vkDestroySurfaceKHR = nullptr;
void* g_pfn_vkDestroySwapchainKHR = nullptr;
void* g_pfn_vkDeviceWaitIdle = nullptr;
void* g_pfn_vkEndCommandBuffer = nullptr;
void* g_pfn_vkEnumerateDeviceExtensionProperties = nullptr;
void* g_pfn_vkEnumerateDeviceLayerProperties = nullptr;
void* g_pfn_vkEnumerateInstanceExtensionProperties = nullptr;
void* g_pfn_vkEnumerateInstanceLayerProperties = nullptr;
void* g_pfn_vkEnumerateInstanceVersion = nullptr;
void* g_pfn_vkEnumeratePhysicalDeviceGroups = nullptr;
void* g_pfn_vkEnumeratePhysicalDevices = nullptr;
void* g_pfn_vkFlushMappedMemoryRanges = nullptr;
void* g_pfn_vkFreeCommandBuffers = nullptr;
void* g_pfn_vkFreeDescriptorSets = nullptr;
void* g_pfn_vkFreeMemory = nullptr;
void* g_pfn_vkGetBufferDeviceAddress = nullptr;
void* g_pfn_vkGetBufferMemoryRequirements = nullptr;
void* g_pfn_vkGetBufferMemoryRequirements2 = nullptr;
void* g_pfn_vkGetBufferOpaqueCaptureAddress = nullptr;
void* g_pfn_vkGetDescriptorSetLayoutSupport = nullptr;
void* g_pfn_vkGetDeviceBufferMemoryRequirements = nullptr;
void* g_pfn_vkGetDeviceGroupPeerMemoryFeatures = nullptr;
void* g_pfn_vkGetDeviceImageMemoryRequirements = nullptr;
void* g_pfn_vkGetDeviceImageSparseMemoryRequirements = nullptr;
void* g_pfn_vkGetDeviceMemoryCommitment = nullptr;
void* g_pfn_vkGetDeviceMemoryOpaqueCaptureAddress = nullptr;
void* g_pfn_vkGetDeviceProcAddr = nullptr;
void* g_pfn_vkGetDeviceQueue = nullptr;
void* g_pfn_vkGetDeviceQueue2 = nullptr;
void* g_pfn_vkGetEventStatus = nullptr;
void* g_pfn_vkGetFenceStatus = nullptr;
void* g_pfn_vkGetImageMemoryRequirements = nullptr;
void* g_pfn_vkGetImageMemoryRequirements2 = nullptr;
void* g_pfn_vkGetImageMemoryRequirements2KHR = nullptr;
void* g_pfn_vkGetImageSparseMemoryRequirements = nullptr;
void* g_pfn_vkGetImageSparseMemoryRequirements2 = nullptr;
void* g_pfn_vkGetImageSubresourceLayout = nullptr;
void* g_pfn_vkGetInstanceProcAddr = nullptr;
void* g_pfn_vkGetPhysicalDeviceExternalBufferProperties = nullptr;
void* g_pfn_vkGetPhysicalDeviceExternalFenceProperties = nullptr;
void* g_pfn_vkGetPhysicalDeviceExternalSemaphoreProperties = nullptr;
void* g_pfn_vkGetPhysicalDeviceFeatures = nullptr;
void* g_pfn_vkGetPhysicalDeviceFeatures2 = nullptr;
void* g_pfn_vkGetPhysicalDeviceFeatures2KHR = nullptr;
void* g_pfn_vkGetPhysicalDeviceFormatProperties = nullptr;
void* g_pfn_vkGetPhysicalDeviceFormatProperties2 = nullptr;
void* g_pfn_vkGetPhysicalDeviceImageFormatProperties = nullptr;
void* g_pfn_vkGetPhysicalDeviceImageFormatProperties2 = nullptr;
void* g_pfn_vkGetPhysicalDeviceMemoryProperties = nullptr;
void* g_pfn_vkGetPhysicalDeviceMemoryProperties2 = nullptr;
void* g_pfn_vkGetPhysicalDeviceProperties = nullptr;
void* g_pfn_vkGetPhysicalDeviceProperties2 = nullptr;
void* g_pfn_vkGetPhysicalDeviceProperties2KHR = nullptr;
void* g_pfn_vkGetPhysicalDeviceQueueFamilyProperties = nullptr;
void* g_pfn_vkGetPhysicalDeviceQueueFamilyProperties2 = nullptr;
void* g_pfn_vkGetPhysicalDeviceSparseImageFormatProperties = nullptr;
void* g_pfn_vkGetPhysicalDeviceSparseImageFormatProperties2 = nullptr;
void* g_pfn_vkGetPhysicalDeviceSurfaceCapabilitiesKHR = nullptr;
void* g_pfn_vkGetPhysicalDeviceSurfaceFormatsKHR = nullptr;
void* g_pfn_vkGetPhysicalDeviceSurfacePresentModesKHR = nullptr;
void* g_pfn_vkGetPhysicalDeviceSurfaceSupportKHR = nullptr;
void* g_pfn_vkGetPhysicalDeviceToolProperties = nullptr;
void* g_pfn_vkGetPipelineCacheData = nullptr;
void* g_pfn_vkGetPrivateData = nullptr;
void* g_pfn_vkGetQueryPoolResults = nullptr;
void* g_pfn_vkGetRenderAreaGranularity = nullptr;
void* g_pfn_vkGetSemaphoreCounterValue = nullptr;
void* g_pfn_vkGetSwapchainImagesKHR = nullptr;
void* g_pfn_vkInvalidateMappedMemoryRanges = nullptr;
void* g_pfn_vkMapMemory = nullptr;
void* g_pfn_vkMergePipelineCaches = nullptr;
void* g_pfn_vkQueueBindSparse = nullptr;
void* g_pfn_vkQueuePresentKHR = nullptr;
void* g_pfn_vkQueueSubmit = nullptr;
void* g_pfn_vkQueueSubmit2 = nullptr;
void* g_pfn_vkQueueWaitIdle = nullptr;
void* g_pfn_vkResetCommandBuffer = nullptr;
void* g_pfn_vkResetCommandPool = nullptr;
void* g_pfn_vkResetDescriptorPool = nullptr;
void* g_pfn_vkResetEvent = nullptr;
void* g_pfn_vkResetFences = nullptr;
void* g_pfn_vkResetQueryPool = nullptr;
void* g_pfn_vkSetEvent = nullptr;
void* g_pfn_vkSetPrivateData = nullptr;
void* g_pfn_vkSignalSemaphore = nullptr;
void* g_pfn_vkTrimCommandPool = nullptr;
void* g_pfn_vkUnmapMemory = nullptr;
void* g_pfn_vkUpdateDescriptorSetWithTemplate = nullptr;
void* g_pfn_vkUpdateDescriptorSets = nullptr;
void* g_pfn_vkWaitForFences = nullptr;
void* g_pfn_vkWaitSemaphores = nullptr;

__asm__(".section .text\n\t"
        ".globl D3D11CreateDevice\n\t"
        "D3D11CreateDevice:\n\t"
        "movq g_pfn_D3D11CreateDevice(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl D3D11CreateDeviceAndSwapChain\n\t"
        "D3D11CreateDeviceAndSwapChain:\n\t"
        "movq g_pfn_D3D11CreateDeviceAndSwapChain(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl D3D12CreateRootSignatureDeserializer\n\t"
        "D3D12CreateRootSignatureDeserializer:\n\t"
        "movq g_pfn_D3D12CreateRootSignatureDeserializer(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl D3D12CreateVersionedRootSignatureDeserializer\n\t"
        "D3D12CreateVersionedRootSignatureDeserializer:\n\t"
        "movq g_pfn_D3D12CreateVersionedRootSignatureDeserializer(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl D3D12EnableExperimentalFeatures\n\t"
        "D3D12EnableExperimentalFeatures:\n\t"
        "movq g_pfn_D3D12EnableExperimentalFeatures(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl D3D12GetDebugInterface\n\t"
        "D3D12GetDebugInterface:\n\t"
        "movq g_pfn_D3D12GetDebugInterface(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl D3D12GetInterface\n\t"
        "D3D12GetInterface:\n\t"
        "movq g_pfn_D3D12GetInterface(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl D3D12SerializeRootSignature\n\t"
        "D3D12SerializeRootSignature:\n\t"
        "movq g_pfn_D3D12SerializeRootSignature(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl D3D12SerializeVersionedRootSignature\n\t"
        "D3D12SerializeVersionedRootSignature:\n\t"
        "movq g_pfn_D3D12SerializeVersionedRootSignature(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkAcquireNextImageKHR\n\t"
        "vkAcquireNextImageKHR:\n\t"
        "movq g_pfn_vkAcquireNextImageKHR(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkAllocateCommandBuffers\n\t"
        "vkAllocateCommandBuffers:\n\t"
        "movq g_pfn_vkAllocateCommandBuffers(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkAllocateDescriptorSets\n\t"
        "vkAllocateDescriptorSets:\n\t"
        "movq g_pfn_vkAllocateDescriptorSets(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkAllocateMemory\n\t"
        "vkAllocateMemory:\n\t"
        "movq g_pfn_vkAllocateMemory(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkBeginCommandBuffer\n\t"
        "vkBeginCommandBuffer:\n\t"
        "movq g_pfn_vkBeginCommandBuffer(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkBindBufferMemory\n\t"
        "vkBindBufferMemory:\n\t"
        "movq g_pfn_vkBindBufferMemory(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkBindBufferMemory2\n\t"
        "vkBindBufferMemory2:\n\t"
        "movq g_pfn_vkBindBufferMemory2(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkBindImageMemory\n\t"
        "vkBindImageMemory:\n\t"
        "movq g_pfn_vkBindImageMemory(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkBindImageMemory2\n\t"
        "vkBindImageMemory2:\n\t"
        "movq g_pfn_vkBindImageMemory2(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdBeginQuery\n\t"
        "vkCmdBeginQuery:\n\t"
        "movq g_pfn_vkCmdBeginQuery(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdBeginRenderPass\n\t"
        "vkCmdBeginRenderPass:\n\t"
        "movq g_pfn_vkCmdBeginRenderPass(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdBeginRenderPass2\n\t"
        "vkCmdBeginRenderPass2:\n\t"
        "movq g_pfn_vkCmdBeginRenderPass2(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdBeginRendering\n\t"
        "vkCmdBeginRendering:\n\t"
        "movq g_pfn_vkCmdBeginRendering(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdBindDescriptorSets\n\t"
        "vkCmdBindDescriptorSets:\n\t"
        "movq g_pfn_vkCmdBindDescriptorSets(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdBindIndexBuffer\n\t"
        "vkCmdBindIndexBuffer:\n\t"
        "movq g_pfn_vkCmdBindIndexBuffer(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdBindPipeline\n\t"
        "vkCmdBindPipeline:\n\t"
        "movq g_pfn_vkCmdBindPipeline(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdBindVertexBuffers\n\t"
        "vkCmdBindVertexBuffers:\n\t"
        "movq g_pfn_vkCmdBindVertexBuffers(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdBindVertexBuffers2\n\t"
        "vkCmdBindVertexBuffers2:\n\t"
        "movq g_pfn_vkCmdBindVertexBuffers2(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdBlitImage\n\t"
        "vkCmdBlitImage:\n\t"
        "movq g_pfn_vkCmdBlitImage(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdBlitImage2\n\t"
        "vkCmdBlitImage2:\n\t"
        "movq g_pfn_vkCmdBlitImage2(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdClearAttachments\n\t"
        "vkCmdClearAttachments:\n\t"
        "movq g_pfn_vkCmdClearAttachments(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdClearColorImage\n\t"
        "vkCmdClearColorImage:\n\t"
        "movq g_pfn_vkCmdClearColorImage(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdClearDepthStencilImage\n\t"
        "vkCmdClearDepthStencilImage:\n\t"
        "movq g_pfn_vkCmdClearDepthStencilImage(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdCopyBuffer\n\t"
        "vkCmdCopyBuffer:\n\t"
        "movq g_pfn_vkCmdCopyBuffer(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdCopyBuffer2\n\t"
        "vkCmdCopyBuffer2:\n\t"
        "movq g_pfn_vkCmdCopyBuffer2(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdCopyBufferToImage\n\t"
        "vkCmdCopyBufferToImage:\n\t"
        "movq g_pfn_vkCmdCopyBufferToImage(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdCopyBufferToImage2\n\t"
        "vkCmdCopyBufferToImage2:\n\t"
        "movq g_pfn_vkCmdCopyBufferToImage2(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdCopyImage\n\t"
        "vkCmdCopyImage:\n\t"
        "movq g_pfn_vkCmdCopyImage(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdCopyImage2\n\t"
        "vkCmdCopyImage2:\n\t"
        "movq g_pfn_vkCmdCopyImage2(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdCopyImageToBuffer\n\t"
        "vkCmdCopyImageToBuffer:\n\t"
        "movq g_pfn_vkCmdCopyImageToBuffer(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdCopyImageToBuffer2\n\t"
        "vkCmdCopyImageToBuffer2:\n\t"
        "movq g_pfn_vkCmdCopyImageToBuffer2(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdCopyQueryPoolResults\n\t"
        "vkCmdCopyQueryPoolResults:\n\t"
        "movq g_pfn_vkCmdCopyQueryPoolResults(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdDispatch\n\t"
        "vkCmdDispatch:\n\t"
        "movq g_pfn_vkCmdDispatch(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdDispatchBase\n\t"
        "vkCmdDispatchBase:\n\t"
        "movq g_pfn_vkCmdDispatchBase(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdDispatchIndirect\n\t"
        "vkCmdDispatchIndirect:\n\t"
        "movq g_pfn_vkCmdDispatchIndirect(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdDraw\n\t"
        "vkCmdDraw:\n\t"
        "movq g_pfn_vkCmdDraw(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdDrawIndexed\n\t"
        "vkCmdDrawIndexed:\n\t"
        "movq g_pfn_vkCmdDrawIndexed(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdDrawIndexedIndirect\n\t"
        "vkCmdDrawIndexedIndirect:\n\t"
        "movq g_pfn_vkCmdDrawIndexedIndirect(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdDrawIndexedIndirectCount\n\t"
        "vkCmdDrawIndexedIndirectCount:\n\t"
        "movq g_pfn_vkCmdDrawIndexedIndirectCount(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdDrawIndirect\n\t"
        "vkCmdDrawIndirect:\n\t"
        "movq g_pfn_vkCmdDrawIndirect(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdDrawIndirectCount\n\t"
        "vkCmdDrawIndirectCount:\n\t"
        "movq g_pfn_vkCmdDrawIndirectCount(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdEndQuery\n\t"
        "vkCmdEndQuery:\n\t"
        "movq g_pfn_vkCmdEndQuery(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdEndRenderPass\n\t"
        "vkCmdEndRenderPass:\n\t"
        "movq g_pfn_vkCmdEndRenderPass(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdEndRenderPass2\n\t"
        "vkCmdEndRenderPass2:\n\t"
        "movq g_pfn_vkCmdEndRenderPass2(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdEndRendering\n\t"
        "vkCmdEndRendering:\n\t"
        "movq g_pfn_vkCmdEndRendering(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdExecuteCommands\n\t"
        "vkCmdExecuteCommands:\n\t"
        "movq g_pfn_vkCmdExecuteCommands(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdFillBuffer\n\t"
        "vkCmdFillBuffer:\n\t"
        "movq g_pfn_vkCmdFillBuffer(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdNextSubpass\n\t"
        "vkCmdNextSubpass:\n\t"
        "movq g_pfn_vkCmdNextSubpass(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdNextSubpass2\n\t"
        "vkCmdNextSubpass2:\n\t"
        "movq g_pfn_vkCmdNextSubpass2(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdPipelineBarrier\n\t"
        "vkCmdPipelineBarrier:\n\t"
        "movq g_pfn_vkCmdPipelineBarrier(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdPipelineBarrier2\n\t"
        "vkCmdPipelineBarrier2:\n\t"
        "movq g_pfn_vkCmdPipelineBarrier2(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdPushConstants\n\t"
        "vkCmdPushConstants:\n\t"
        "movq g_pfn_vkCmdPushConstants(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdResetEvent\n\t"
        "vkCmdResetEvent:\n\t"
        "movq g_pfn_vkCmdResetEvent(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdResetEvent2\n\t"
        "vkCmdResetEvent2:\n\t"
        "movq g_pfn_vkCmdResetEvent2(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdResetQueryPool\n\t"
        "vkCmdResetQueryPool:\n\t"
        "movq g_pfn_vkCmdResetQueryPool(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdResolveImage\n\t"
        "vkCmdResolveImage:\n\t"
        "movq g_pfn_vkCmdResolveImage(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdResolveImage2\n\t"
        "vkCmdResolveImage2:\n\t"
        "movq g_pfn_vkCmdResolveImage2(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdSetBlendConstants\n\t"
        "vkCmdSetBlendConstants:\n\t"
        "movq g_pfn_vkCmdSetBlendConstants(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdSetCullMode\n\t"
        "vkCmdSetCullMode:\n\t"
        "movq g_pfn_vkCmdSetCullMode(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdSetDepthBias\n\t"
        "vkCmdSetDepthBias:\n\t"
        "movq g_pfn_vkCmdSetDepthBias(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdSetDepthBiasEnable\n\t"
        "vkCmdSetDepthBiasEnable:\n\t"
        "movq g_pfn_vkCmdSetDepthBiasEnable(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdSetDepthBounds\n\t"
        "vkCmdSetDepthBounds:\n\t"
        "movq g_pfn_vkCmdSetDepthBounds(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdSetDepthBoundsTestEnable\n\t"
        "vkCmdSetDepthBoundsTestEnable:\n\t"
        "movq g_pfn_vkCmdSetDepthBoundsTestEnable(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdSetDepthCompareOp\n\t"
        "vkCmdSetDepthCompareOp:\n\t"
        "movq g_pfn_vkCmdSetDepthCompareOp(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdSetDepthTestEnable\n\t"
        "vkCmdSetDepthTestEnable:\n\t"
        "movq g_pfn_vkCmdSetDepthTestEnable(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdSetDepthWriteEnable\n\t"
        "vkCmdSetDepthWriteEnable:\n\t"
        "movq g_pfn_vkCmdSetDepthWriteEnable(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdSetDeviceMask\n\t"
        "vkCmdSetDeviceMask:\n\t"
        "movq g_pfn_vkCmdSetDeviceMask(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdSetEvent\n\t"
        "vkCmdSetEvent:\n\t"
        "movq g_pfn_vkCmdSetEvent(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdSetEvent2\n\t"
        "vkCmdSetEvent2:\n\t"
        "movq g_pfn_vkCmdSetEvent2(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdSetFrontFace\n\t"
        "vkCmdSetFrontFace:\n\t"
        "movq g_pfn_vkCmdSetFrontFace(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdSetLineWidth\n\t"
        "vkCmdSetLineWidth:\n\t"
        "movq g_pfn_vkCmdSetLineWidth(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdSetPrimitiveRestartEnable\n\t"
        "vkCmdSetPrimitiveRestartEnable:\n\t"
        "movq g_pfn_vkCmdSetPrimitiveRestartEnable(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdSetPrimitiveTopology\n\t"
        "vkCmdSetPrimitiveTopology:\n\t"
        "movq g_pfn_vkCmdSetPrimitiveTopology(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdSetRasterizerDiscardEnable\n\t"
        "vkCmdSetRasterizerDiscardEnable:\n\t"
        "movq g_pfn_vkCmdSetRasterizerDiscardEnable(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdSetScissor\n\t"
        "vkCmdSetScissor:\n\t"
        "movq g_pfn_vkCmdSetScissor(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdSetScissorWithCount\n\t"
        "vkCmdSetScissorWithCount:\n\t"
        "movq g_pfn_vkCmdSetScissorWithCount(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdSetStencilCompareMask\n\t"
        "vkCmdSetStencilCompareMask:\n\t"
        "movq g_pfn_vkCmdSetStencilCompareMask(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdSetStencilOp\n\t"
        "vkCmdSetStencilOp:\n\t"
        "movq g_pfn_vkCmdSetStencilOp(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdSetStencilReference\n\t"
        "vkCmdSetStencilReference:\n\t"
        "movq g_pfn_vkCmdSetStencilReference(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdSetStencilTestEnable\n\t"
        "vkCmdSetStencilTestEnable:\n\t"
        "movq g_pfn_vkCmdSetStencilTestEnable(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdSetStencilWriteMask\n\t"
        "vkCmdSetStencilWriteMask:\n\t"
        "movq g_pfn_vkCmdSetStencilWriteMask(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdSetViewport\n\t"
        "vkCmdSetViewport:\n\t"
        "movq g_pfn_vkCmdSetViewport(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdSetViewportWithCount\n\t"
        "vkCmdSetViewportWithCount:\n\t"
        "movq g_pfn_vkCmdSetViewportWithCount(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdUpdateBuffer\n\t"
        "vkCmdUpdateBuffer:\n\t"
        "movq g_pfn_vkCmdUpdateBuffer(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdWaitEvents\n\t"
        "vkCmdWaitEvents:\n\t"
        "movq g_pfn_vkCmdWaitEvents(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdWaitEvents2\n\t"
        "vkCmdWaitEvents2:\n\t"
        "movq g_pfn_vkCmdWaitEvents2(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdWriteTimestamp\n\t"
        "vkCmdWriteTimestamp:\n\t"
        "movq g_pfn_vkCmdWriteTimestamp(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCmdWriteTimestamp2\n\t"
        "vkCmdWriteTimestamp2:\n\t"
        "movq g_pfn_vkCmdWriteTimestamp2(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCreateBuffer\n\t"
        "vkCreateBuffer:\n\t"
        "movq g_pfn_vkCreateBuffer(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCreateBufferView\n\t"
        "vkCreateBufferView:\n\t"
        "movq g_pfn_vkCreateBufferView(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCreateCommandPool\n\t"
        "vkCreateCommandPool:\n\t"
        "movq g_pfn_vkCreateCommandPool(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCreateComputePipelines\n\t"
        "vkCreateComputePipelines:\n\t"
        "movq g_pfn_vkCreateComputePipelines(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCreateDescriptorPool\n\t"
        "vkCreateDescriptorPool:\n\t"
        "movq g_pfn_vkCreateDescriptorPool(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCreateDescriptorSetLayout\n\t"
        "vkCreateDescriptorSetLayout:\n\t"
        "movq g_pfn_vkCreateDescriptorSetLayout(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCreateDescriptorUpdateTemplate\n\t"
        "vkCreateDescriptorUpdateTemplate:\n\t"
        "movq g_pfn_vkCreateDescriptorUpdateTemplate(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCreateDevice\n\t"
        "vkCreateDevice:\n\t"
        "movq g_pfn_vkCreateDevice(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCreateEvent\n\t"
        "vkCreateEvent:\n\t"
        "movq g_pfn_vkCreateEvent(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCreateFence\n\t"
        "vkCreateFence:\n\t"
        "movq g_pfn_vkCreateFence(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCreateFramebuffer\n\t"
        "vkCreateFramebuffer:\n\t"
        "movq g_pfn_vkCreateFramebuffer(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCreateGraphicsPipelines\n\t"
        "vkCreateGraphicsPipelines:\n\t"
        "movq g_pfn_vkCreateGraphicsPipelines(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCreateImage\n\t"
        "vkCreateImage:\n\t"
        "movq g_pfn_vkCreateImage(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCreateImageView\n\t"
        "vkCreateImageView:\n\t"
        "movq g_pfn_vkCreateImageView(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCreateInstance\n\t"
        "vkCreateInstance:\n\t"
        "movq g_pfn_vkCreateInstance(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCreatePipelineCache\n\t"
        "vkCreatePipelineCache:\n\t"
        "movq g_pfn_vkCreatePipelineCache(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCreatePipelineLayout\n\t"
        "vkCreatePipelineLayout:\n\t"
        "movq g_pfn_vkCreatePipelineLayout(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCreatePrivateDataSlot\n\t"
        "vkCreatePrivateDataSlot:\n\t"
        "movq g_pfn_vkCreatePrivateDataSlot(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCreateQueryPool\n\t"
        "vkCreateQueryPool:\n\t"
        "movq g_pfn_vkCreateQueryPool(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCreateRenderPass\n\t"
        "vkCreateRenderPass:\n\t"
        "movq g_pfn_vkCreateRenderPass(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCreateRenderPass2\n\t"
        "vkCreateRenderPass2:\n\t"
        "movq g_pfn_vkCreateRenderPass2(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCreateSampler\n\t"
        "vkCreateSampler:\n\t"
        "movq g_pfn_vkCreateSampler(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCreateSamplerYcbcrConversion\n\t"
        "vkCreateSamplerYcbcrConversion:\n\t"
        "movq g_pfn_vkCreateSamplerYcbcrConversion(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCreateSemaphore\n\t"
        "vkCreateSemaphore:\n\t"
        "movq g_pfn_vkCreateSemaphore(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCreateShaderModule\n\t"
        "vkCreateShaderModule:\n\t"
        "movq g_pfn_vkCreateShaderModule(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCreateSwapchainKHR\n\t"
        "vkCreateSwapchainKHR:\n\t"
        "movq g_pfn_vkCreateSwapchainKHR(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkCreateWin32SurfaceKHR\n\t"
        "vkCreateWin32SurfaceKHR:\n\t"
        "movq g_pfn_vkCreateWin32SurfaceKHR(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkDestroyBuffer\n\t"
        "vkDestroyBuffer:\n\t"
        "movq g_pfn_vkDestroyBuffer(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkDestroyBufferView\n\t"
        "vkDestroyBufferView:\n\t"
        "movq g_pfn_vkDestroyBufferView(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkDestroyCommandPool\n\t"
        "vkDestroyCommandPool:\n\t"
        "movq g_pfn_vkDestroyCommandPool(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkDestroyDescriptorPool\n\t"
        "vkDestroyDescriptorPool:\n\t"
        "movq g_pfn_vkDestroyDescriptorPool(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkDestroyDescriptorSetLayout\n\t"
        "vkDestroyDescriptorSetLayout:\n\t"
        "movq g_pfn_vkDestroyDescriptorSetLayout(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkDestroyDescriptorUpdateTemplate\n\t"
        "vkDestroyDescriptorUpdateTemplate:\n\t"
        "movq g_pfn_vkDestroyDescriptorUpdateTemplate(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkDestroyDevice\n\t"
        "vkDestroyDevice:\n\t"
        "movq g_pfn_vkDestroyDevice(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkDestroyEvent\n\t"
        "vkDestroyEvent:\n\t"
        "movq g_pfn_vkDestroyEvent(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkDestroyFence\n\t"
        "vkDestroyFence:\n\t"
        "movq g_pfn_vkDestroyFence(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkDestroyFramebuffer\n\t"
        "vkDestroyFramebuffer:\n\t"
        "movq g_pfn_vkDestroyFramebuffer(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkDestroyImage\n\t"
        "vkDestroyImage:\n\t"
        "movq g_pfn_vkDestroyImage(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkDestroyImageView\n\t"
        "vkDestroyImageView:\n\t"
        "movq g_pfn_vkDestroyImageView(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkDestroyInstance\n\t"
        "vkDestroyInstance:\n\t"
        "movq g_pfn_vkDestroyInstance(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkDestroyPipeline\n\t"
        "vkDestroyPipeline:\n\t"
        "movq g_pfn_vkDestroyPipeline(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkDestroyPipelineCache\n\t"
        "vkDestroyPipelineCache:\n\t"
        "movq g_pfn_vkDestroyPipelineCache(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkDestroyPipelineLayout\n\t"
        "vkDestroyPipelineLayout:\n\t"
        "movq g_pfn_vkDestroyPipelineLayout(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkDestroyPrivateDataSlot\n\t"
        "vkDestroyPrivateDataSlot:\n\t"
        "movq g_pfn_vkDestroyPrivateDataSlot(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkDestroyQueryPool\n\t"
        "vkDestroyQueryPool:\n\t"
        "movq g_pfn_vkDestroyQueryPool(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkDestroyRenderPass\n\t"
        "vkDestroyRenderPass:\n\t"
        "movq g_pfn_vkDestroyRenderPass(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkDestroySampler\n\t"
        "vkDestroySampler:\n\t"
        "movq g_pfn_vkDestroySampler(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkDestroySamplerYcbcrConversion\n\t"
        "vkDestroySamplerYcbcrConversion:\n\t"
        "movq g_pfn_vkDestroySamplerYcbcrConversion(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkDestroySemaphore\n\t"
        "vkDestroySemaphore:\n\t"
        "movq g_pfn_vkDestroySemaphore(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkDestroyShaderModule\n\t"
        "vkDestroyShaderModule:\n\t"
        "movq g_pfn_vkDestroyShaderModule(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkDestroySurfaceKHR\n\t"
        "vkDestroySurfaceKHR:\n\t"
        "movq g_pfn_vkDestroySurfaceKHR(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkDestroySwapchainKHR\n\t"
        "vkDestroySwapchainKHR:\n\t"
        "movq g_pfn_vkDestroySwapchainKHR(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkDeviceWaitIdle\n\t"
        "vkDeviceWaitIdle:\n\t"
        "movq g_pfn_vkDeviceWaitIdle(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkEndCommandBuffer\n\t"
        "vkEndCommandBuffer:\n\t"
        "movq g_pfn_vkEndCommandBuffer(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkEnumerateDeviceExtensionProperties\n\t"
        "vkEnumerateDeviceExtensionProperties:\n\t"
        "movq g_pfn_vkEnumerateDeviceExtensionProperties(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkEnumerateDeviceLayerProperties\n\t"
        "vkEnumerateDeviceLayerProperties:\n\t"
        "movq g_pfn_vkEnumerateDeviceLayerProperties(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkEnumerateInstanceExtensionProperties\n\t"
        "vkEnumerateInstanceExtensionProperties:\n\t"
        "movq g_pfn_vkEnumerateInstanceExtensionProperties(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkEnumerateInstanceLayerProperties\n\t"
        "vkEnumerateInstanceLayerProperties:\n\t"
        "movq g_pfn_vkEnumerateInstanceLayerProperties(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkEnumerateInstanceVersion\n\t"
        "vkEnumerateInstanceVersion:\n\t"
        "movq g_pfn_vkEnumerateInstanceVersion(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkEnumeratePhysicalDeviceGroups\n\t"
        "vkEnumeratePhysicalDeviceGroups:\n\t"
        "movq g_pfn_vkEnumeratePhysicalDeviceGroups(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkEnumeratePhysicalDevices\n\t"
        "vkEnumeratePhysicalDevices:\n\t"
        "movq g_pfn_vkEnumeratePhysicalDevices(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkFlushMappedMemoryRanges\n\t"
        "vkFlushMappedMemoryRanges:\n\t"
        "movq g_pfn_vkFlushMappedMemoryRanges(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkFreeCommandBuffers\n\t"
        "vkFreeCommandBuffers:\n\t"
        "movq g_pfn_vkFreeCommandBuffers(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkFreeDescriptorSets\n\t"
        "vkFreeDescriptorSets:\n\t"
        "movq g_pfn_vkFreeDescriptorSets(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkFreeMemory\n\t"
        "vkFreeMemory:\n\t"
        "movq g_pfn_vkFreeMemory(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkGetBufferDeviceAddress\n\t"
        "vkGetBufferDeviceAddress:\n\t"
        "movq g_pfn_vkGetBufferDeviceAddress(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkGetBufferMemoryRequirements\n\t"
        "vkGetBufferMemoryRequirements:\n\t"
        "movq g_pfn_vkGetBufferMemoryRequirements(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkGetBufferMemoryRequirements2\n\t"
        "vkGetBufferMemoryRequirements2:\n\t"
        "movq g_pfn_vkGetBufferMemoryRequirements2(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkGetBufferOpaqueCaptureAddress\n\t"
        "vkGetBufferOpaqueCaptureAddress:\n\t"
        "movq g_pfn_vkGetBufferOpaqueCaptureAddress(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkGetDescriptorSetLayoutSupport\n\t"
        "vkGetDescriptorSetLayoutSupport:\n\t"
        "movq g_pfn_vkGetDescriptorSetLayoutSupport(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkGetDeviceBufferMemoryRequirements\n\t"
        "vkGetDeviceBufferMemoryRequirements:\n\t"
        "movq g_pfn_vkGetDeviceBufferMemoryRequirements(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkGetDeviceGroupPeerMemoryFeatures\n\t"
        "vkGetDeviceGroupPeerMemoryFeatures:\n\t"
        "movq g_pfn_vkGetDeviceGroupPeerMemoryFeatures(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkGetDeviceImageMemoryRequirements\n\t"
        "vkGetDeviceImageMemoryRequirements:\n\t"
        "movq g_pfn_vkGetDeviceImageMemoryRequirements(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkGetDeviceImageSparseMemoryRequirements\n\t"
        "vkGetDeviceImageSparseMemoryRequirements:\n\t"
        "movq g_pfn_vkGetDeviceImageSparseMemoryRequirements(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkGetDeviceMemoryCommitment\n\t"
        "vkGetDeviceMemoryCommitment:\n\t"
        "movq g_pfn_vkGetDeviceMemoryCommitment(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkGetDeviceMemoryOpaqueCaptureAddress\n\t"
        "vkGetDeviceMemoryOpaqueCaptureAddress:\n\t"
        "movq g_pfn_vkGetDeviceMemoryOpaqueCaptureAddress(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkGetDeviceProcAddr\n\t"
        "vkGetDeviceProcAddr:\n\t"
        "movq g_pfn_vkGetDeviceProcAddr(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkGetDeviceQueue\n\t"
        "vkGetDeviceQueue:\n\t"
        "movq g_pfn_vkGetDeviceQueue(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkGetDeviceQueue2\n\t"
        "vkGetDeviceQueue2:\n\t"
        "movq g_pfn_vkGetDeviceQueue2(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkGetEventStatus\n\t"
        "vkGetEventStatus:\n\t"
        "movq g_pfn_vkGetEventStatus(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkGetFenceStatus\n\t"
        "vkGetFenceStatus:\n\t"
        "movq g_pfn_vkGetFenceStatus(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkGetImageMemoryRequirements\n\t"
        "vkGetImageMemoryRequirements:\n\t"
        "movq g_pfn_vkGetImageMemoryRequirements(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkGetImageMemoryRequirements2\n\t"
        "vkGetImageMemoryRequirements2:\n\t"
        "movq g_pfn_vkGetImageMemoryRequirements2(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkGetImageMemoryRequirements2KHR\n\t"
        "vkGetImageMemoryRequirements2KHR:\n\t"
        "movq g_pfn_vkGetImageMemoryRequirements2KHR(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkGetImageSparseMemoryRequirements\n\t"
        "vkGetImageSparseMemoryRequirements:\n\t"
        "movq g_pfn_vkGetImageSparseMemoryRequirements(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkGetImageSparseMemoryRequirements2\n\t"
        "vkGetImageSparseMemoryRequirements2:\n\t"
        "movq g_pfn_vkGetImageSparseMemoryRequirements2(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkGetImageSubresourceLayout\n\t"
        "vkGetImageSubresourceLayout:\n\t"
        "movq g_pfn_vkGetImageSubresourceLayout(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkGetInstanceProcAddr\n\t"
        "vkGetInstanceProcAddr:\n\t"
        "movq g_pfn_vkGetInstanceProcAddr(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkGetPhysicalDeviceExternalBufferProperties\n\t"
        "vkGetPhysicalDeviceExternalBufferProperties:\n\t"
        "movq g_pfn_vkGetPhysicalDeviceExternalBufferProperties(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkGetPhysicalDeviceExternalFenceProperties\n\t"
        "vkGetPhysicalDeviceExternalFenceProperties:\n\t"
        "movq g_pfn_vkGetPhysicalDeviceExternalFenceProperties(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkGetPhysicalDeviceExternalSemaphoreProperties\n\t"
        "vkGetPhysicalDeviceExternalSemaphoreProperties:\n\t"
        "movq g_pfn_vkGetPhysicalDeviceExternalSemaphoreProperties(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkGetPhysicalDeviceFeatures\n\t"
        "vkGetPhysicalDeviceFeatures:\n\t"
        "movq g_pfn_vkGetPhysicalDeviceFeatures(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkGetPhysicalDeviceFeatures2\n\t"
        "vkGetPhysicalDeviceFeatures2:\n\t"
        "movq g_pfn_vkGetPhysicalDeviceFeatures2(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkGetPhysicalDeviceFeatures2KHR\n\t"
        "vkGetPhysicalDeviceFeatures2KHR:\n\t"
        "movq g_pfn_vkGetPhysicalDeviceFeatures2KHR(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkGetPhysicalDeviceFormatProperties\n\t"
        "vkGetPhysicalDeviceFormatProperties:\n\t"
        "movq g_pfn_vkGetPhysicalDeviceFormatProperties(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkGetPhysicalDeviceFormatProperties2\n\t"
        "vkGetPhysicalDeviceFormatProperties2:\n\t"
        "movq g_pfn_vkGetPhysicalDeviceFormatProperties2(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkGetPhysicalDeviceImageFormatProperties\n\t"
        "vkGetPhysicalDeviceImageFormatProperties:\n\t"
        "movq g_pfn_vkGetPhysicalDeviceImageFormatProperties(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkGetPhysicalDeviceImageFormatProperties2\n\t"
        "vkGetPhysicalDeviceImageFormatProperties2:\n\t"
        "movq g_pfn_vkGetPhysicalDeviceImageFormatProperties2(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkGetPhysicalDeviceMemoryProperties\n\t"
        "vkGetPhysicalDeviceMemoryProperties:\n\t"
        "movq g_pfn_vkGetPhysicalDeviceMemoryProperties(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkGetPhysicalDeviceMemoryProperties2\n\t"
        "vkGetPhysicalDeviceMemoryProperties2:\n\t"
        "movq g_pfn_vkGetPhysicalDeviceMemoryProperties2(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkGetPhysicalDeviceProperties\n\t"
        "vkGetPhysicalDeviceProperties:\n\t"
        "movq g_pfn_vkGetPhysicalDeviceProperties(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkGetPhysicalDeviceProperties2\n\t"
        "vkGetPhysicalDeviceProperties2:\n\t"
        "movq g_pfn_vkGetPhysicalDeviceProperties2(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkGetPhysicalDeviceProperties2KHR\n\t"
        "vkGetPhysicalDeviceProperties2KHR:\n\t"
        "movq g_pfn_vkGetPhysicalDeviceProperties2KHR(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkGetPhysicalDeviceQueueFamilyProperties\n\t"
        "vkGetPhysicalDeviceQueueFamilyProperties:\n\t"
        "movq g_pfn_vkGetPhysicalDeviceQueueFamilyProperties(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkGetPhysicalDeviceQueueFamilyProperties2\n\t"
        "vkGetPhysicalDeviceQueueFamilyProperties2:\n\t"
        "movq g_pfn_vkGetPhysicalDeviceQueueFamilyProperties2(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkGetPhysicalDeviceSparseImageFormatProperties\n\t"
        "vkGetPhysicalDeviceSparseImageFormatProperties:\n\t"
        "movq g_pfn_vkGetPhysicalDeviceSparseImageFormatProperties(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkGetPhysicalDeviceSparseImageFormatProperties2\n\t"
        "vkGetPhysicalDeviceSparseImageFormatProperties2:\n\t"
        "movq g_pfn_vkGetPhysicalDeviceSparseImageFormatProperties2(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkGetPhysicalDeviceSurfaceCapabilitiesKHR\n\t"
        "vkGetPhysicalDeviceSurfaceCapabilitiesKHR:\n\t"
        "movq g_pfn_vkGetPhysicalDeviceSurfaceCapabilitiesKHR(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkGetPhysicalDeviceSurfaceFormatsKHR\n\t"
        "vkGetPhysicalDeviceSurfaceFormatsKHR:\n\t"
        "movq g_pfn_vkGetPhysicalDeviceSurfaceFormatsKHR(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkGetPhysicalDeviceSurfacePresentModesKHR\n\t"
        "vkGetPhysicalDeviceSurfacePresentModesKHR:\n\t"
        "movq g_pfn_vkGetPhysicalDeviceSurfacePresentModesKHR(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkGetPhysicalDeviceSurfaceSupportKHR\n\t"
        "vkGetPhysicalDeviceSurfaceSupportKHR:\n\t"
        "movq g_pfn_vkGetPhysicalDeviceSurfaceSupportKHR(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkGetPhysicalDeviceToolProperties\n\t"
        "vkGetPhysicalDeviceToolProperties:\n\t"
        "movq g_pfn_vkGetPhysicalDeviceToolProperties(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkGetPipelineCacheData\n\t"
        "vkGetPipelineCacheData:\n\t"
        "movq g_pfn_vkGetPipelineCacheData(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkGetPrivateData\n\t"
        "vkGetPrivateData:\n\t"
        "movq g_pfn_vkGetPrivateData(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkGetQueryPoolResults\n\t"
        "vkGetQueryPoolResults:\n\t"
        "movq g_pfn_vkGetQueryPoolResults(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkGetRenderAreaGranularity\n\t"
        "vkGetRenderAreaGranularity:\n\t"
        "movq g_pfn_vkGetRenderAreaGranularity(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkGetSemaphoreCounterValue\n\t"
        "vkGetSemaphoreCounterValue:\n\t"
        "movq g_pfn_vkGetSemaphoreCounterValue(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkGetSwapchainImagesKHR\n\t"
        "vkGetSwapchainImagesKHR:\n\t"
        "movq g_pfn_vkGetSwapchainImagesKHR(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkInvalidateMappedMemoryRanges\n\t"
        "vkInvalidateMappedMemoryRanges:\n\t"
        "movq g_pfn_vkInvalidateMappedMemoryRanges(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkMapMemory\n\t"
        "vkMapMemory:\n\t"
        "movq g_pfn_vkMapMemory(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkMergePipelineCaches\n\t"
        "vkMergePipelineCaches:\n\t"
        "movq g_pfn_vkMergePipelineCaches(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkQueueBindSparse\n\t"
        "vkQueueBindSparse:\n\t"
        "movq g_pfn_vkQueueBindSparse(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkQueuePresentKHR\n\t"
        "vkQueuePresentKHR:\n\t"
        "movq g_pfn_vkQueuePresentKHR(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkQueueSubmit\n\t"
        "vkQueueSubmit:\n\t"
        "movq g_pfn_vkQueueSubmit(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkQueueSubmit2\n\t"
        "vkQueueSubmit2:\n\t"
        "movq g_pfn_vkQueueSubmit2(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkQueueWaitIdle\n\t"
        "vkQueueWaitIdle:\n\t"
        "movq g_pfn_vkQueueWaitIdle(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkResetCommandBuffer\n\t"
        "vkResetCommandBuffer:\n\t"
        "movq g_pfn_vkResetCommandBuffer(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkResetCommandPool\n\t"
        "vkResetCommandPool:\n\t"
        "movq g_pfn_vkResetCommandPool(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkResetDescriptorPool\n\t"
        "vkResetDescriptorPool:\n\t"
        "movq g_pfn_vkResetDescriptorPool(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkResetEvent\n\t"
        "vkResetEvent:\n\t"
        "movq g_pfn_vkResetEvent(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkResetFences\n\t"
        "vkResetFences:\n\t"
        "movq g_pfn_vkResetFences(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkResetQueryPool\n\t"
        "vkResetQueryPool:\n\t"
        "movq g_pfn_vkResetQueryPool(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkSetEvent\n\t"
        "vkSetEvent:\n\t"
        "movq g_pfn_vkSetEvent(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkSetPrivateData\n\t"
        "vkSetPrivateData:\n\t"
        "movq g_pfn_vkSetPrivateData(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkSignalSemaphore\n\t"
        "vkSignalSemaphore:\n\t"
        "movq g_pfn_vkSignalSemaphore(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkTrimCommandPool\n\t"
        "vkTrimCommandPool:\n\t"
        "movq g_pfn_vkTrimCommandPool(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkUnmapMemory\n\t"
        "vkUnmapMemory:\n\t"
        "movq g_pfn_vkUnmapMemory(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkUpdateDescriptorSetWithTemplate\n\t"
        "vkUpdateDescriptorSetWithTemplate:\n\t"
        "movq g_pfn_vkUpdateDescriptorSetWithTemplate(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkUpdateDescriptorSets\n\t"
        "vkUpdateDescriptorSets:\n\t"
        "movq g_pfn_vkUpdateDescriptorSets(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkWaitForFences\n\t"
        "vkWaitForFences:\n\t"
        "movq g_pfn_vkWaitForFences(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

__asm__(".section .text\n\t"
        ".globl vkWaitSemaphores\n\t"
        "vkWaitSemaphores:\n\t"
        "movq g_pfn_vkWaitSemaphores(%rip), %rax\n\t"
        "jmpq *%rax\n\t");

static void InitD3D11Forwarders(HMODULE h) {
    g_pfn_D3D11CreateDevice = (void*)GetProcAddress(h, "D3D11CreateDevice");
    g_pfn_D3D11CreateDeviceAndSwapChain = (void*)GetProcAddress(h, "D3D11CreateDeviceAndSwapChain");
}

static void InitD3D12Forwarders(HMODULE h) {
    g_pfn_D3D12CreateRootSignatureDeserializer = (void*)GetProcAddress(h, "D3D12CreateRootSignatureDeserializer");
    g_pfn_D3D12CreateVersionedRootSignatureDeserializer = (void*)GetProcAddress(h, "D3D12CreateVersionedRootSignatureDeserializer");
    g_pfn_D3D12EnableExperimentalFeatures = (void*)GetProcAddress(h, "D3D12EnableExperimentalFeatures");
    g_pfn_D3D12GetDebugInterface = (void*)GetProcAddress(h, "D3D12GetDebugInterface");
    g_pfn_D3D12GetInterface = (void*)GetProcAddress(h, "D3D12GetInterface");
    g_pfn_D3D12SerializeRootSignature = (void*)GetProcAddress(h, "D3D12SerializeRootSignature");
    g_pfn_D3D12SerializeVersionedRootSignature = (void*)GetProcAddress(h, "D3D12SerializeVersionedRootSignature");
}

static void InitVkForwarders(HMODULE h) {
    g_pfn_vkAcquireNextImageKHR = (void*)GetProcAddress(h, "vkAcquireNextImageKHR");
    g_pfn_vkAllocateCommandBuffers = (void*)GetProcAddress(h, "vkAllocateCommandBuffers");
    g_pfn_vkAllocateDescriptorSets = (void*)GetProcAddress(h, "vkAllocateDescriptorSets");
    g_pfn_vkAllocateMemory = (void*)GetProcAddress(h, "vkAllocateMemory");
    g_pfn_vkBeginCommandBuffer = (void*)GetProcAddress(h, "vkBeginCommandBuffer");
    g_pfn_vkBindBufferMemory = (void*)GetProcAddress(h, "vkBindBufferMemory");
    g_pfn_vkBindBufferMemory2 = (void*)GetProcAddress(h, "vkBindBufferMemory2");
    g_pfn_vkBindImageMemory = (void*)GetProcAddress(h, "vkBindImageMemory");
    g_pfn_vkBindImageMemory2 = (void*)GetProcAddress(h, "vkBindImageMemory2");
    g_pfn_vkCmdBeginQuery = (void*)GetProcAddress(h, "vkCmdBeginQuery");
    g_pfn_vkCmdBeginRenderPass = (void*)GetProcAddress(h, "vkCmdBeginRenderPass");
    g_pfn_vkCmdBeginRenderPass2 = (void*)GetProcAddress(h, "vkCmdBeginRenderPass2");
    g_pfn_vkCmdBeginRendering = (void*)GetProcAddress(h, "vkCmdBeginRendering");
    g_pfn_vkCmdBindDescriptorSets = (void*)GetProcAddress(h, "vkCmdBindDescriptorSets");
    g_pfn_vkCmdBindIndexBuffer = (void*)GetProcAddress(h, "vkCmdBindIndexBuffer");
    g_pfn_vkCmdBindPipeline = (void*)GetProcAddress(h, "vkCmdBindPipeline");
    g_pfn_vkCmdBindVertexBuffers = (void*)GetProcAddress(h, "vkCmdBindVertexBuffers");
    g_pfn_vkCmdBindVertexBuffers2 = (void*)GetProcAddress(h, "vkCmdBindVertexBuffers2");
    g_pfn_vkCmdBlitImage = (void*)GetProcAddress(h, "vkCmdBlitImage");
    g_pfn_vkCmdBlitImage2 = (void*)GetProcAddress(h, "vkCmdBlitImage2");
    g_pfn_vkCmdClearAttachments = (void*)GetProcAddress(h, "vkCmdClearAttachments");
    g_pfn_vkCmdClearColorImage = (void*)GetProcAddress(h, "vkCmdClearColorImage");
    g_pfn_vkCmdClearDepthStencilImage = (void*)GetProcAddress(h, "vkCmdClearDepthStencilImage");
    g_pfn_vkCmdCopyBuffer = (void*)GetProcAddress(h, "vkCmdCopyBuffer");
    g_pfn_vkCmdCopyBuffer2 = (void*)GetProcAddress(h, "vkCmdCopyBuffer2");
    g_pfn_vkCmdCopyBufferToImage = (void*)GetProcAddress(h, "vkCmdCopyBufferToImage");
    g_pfn_vkCmdCopyBufferToImage2 = (void*)GetProcAddress(h, "vkCmdCopyBufferToImage2");
    g_pfn_vkCmdCopyImage = (void*)GetProcAddress(h, "vkCmdCopyImage");
    g_pfn_vkCmdCopyImage2 = (void*)GetProcAddress(h, "vkCmdCopyImage2");
    g_pfn_vkCmdCopyImageToBuffer = (void*)GetProcAddress(h, "vkCmdCopyImageToBuffer");
    g_pfn_vkCmdCopyImageToBuffer2 = (void*)GetProcAddress(h, "vkCmdCopyImageToBuffer2");
    g_pfn_vkCmdCopyQueryPoolResults = (void*)GetProcAddress(h, "vkCmdCopyQueryPoolResults");
    g_pfn_vkCmdDispatch = (void*)GetProcAddress(h, "vkCmdDispatch");
    g_pfn_vkCmdDispatchBase = (void*)GetProcAddress(h, "vkCmdDispatchBase");
    g_pfn_vkCmdDispatchIndirect = (void*)GetProcAddress(h, "vkCmdDispatchIndirect");
    g_pfn_vkCmdDraw = (void*)GetProcAddress(h, "vkCmdDraw");
    g_pfn_vkCmdDrawIndexed = (void*)GetProcAddress(h, "vkCmdDrawIndexed");
    g_pfn_vkCmdDrawIndexedIndirect = (void*)GetProcAddress(h, "vkCmdDrawIndexedIndirect");
    g_pfn_vkCmdDrawIndexedIndirectCount = (void*)GetProcAddress(h, "vkCmdDrawIndexedIndirectCount");
    g_pfn_vkCmdDrawIndirect = (void*)GetProcAddress(h, "vkCmdDrawIndirect");
    g_pfn_vkCmdDrawIndirectCount = (void*)GetProcAddress(h, "vkCmdDrawIndirectCount");
    g_pfn_vkCmdEndQuery = (void*)GetProcAddress(h, "vkCmdEndQuery");
    g_pfn_vkCmdEndRenderPass = (void*)GetProcAddress(h, "vkCmdEndRenderPass");
    g_pfn_vkCmdEndRenderPass2 = (void*)GetProcAddress(h, "vkCmdEndRenderPass2");
    g_pfn_vkCmdEndRendering = (void*)GetProcAddress(h, "vkCmdEndRendering");
    g_pfn_vkCmdExecuteCommands = (void*)GetProcAddress(h, "vkCmdExecuteCommands");
    g_pfn_vkCmdFillBuffer = (void*)GetProcAddress(h, "vkCmdFillBuffer");
    g_pfn_vkCmdNextSubpass = (void*)GetProcAddress(h, "vkCmdNextSubpass");
    g_pfn_vkCmdNextSubpass2 = (void*)GetProcAddress(h, "vkCmdNextSubpass2");
    g_pfn_vkCmdPipelineBarrier = (void*)GetProcAddress(h, "vkCmdPipelineBarrier");
    g_pfn_vkCmdPipelineBarrier2 = (void*)GetProcAddress(h, "vkCmdPipelineBarrier2");
    g_pfn_vkCmdPushConstants = (void*)GetProcAddress(h, "vkCmdPushConstants");
    g_pfn_vkCmdResetEvent = (void*)GetProcAddress(h, "vkCmdResetEvent");
    g_pfn_vkCmdResetEvent2 = (void*)GetProcAddress(h, "vkCmdResetEvent2");
    g_pfn_vkCmdResetQueryPool = (void*)GetProcAddress(h, "vkCmdResetQueryPool");
    g_pfn_vkCmdResolveImage = (void*)GetProcAddress(h, "vkCmdResolveImage");
    g_pfn_vkCmdResolveImage2 = (void*)GetProcAddress(h, "vkCmdResolveImage2");
    g_pfn_vkCmdSetBlendConstants = (void*)GetProcAddress(h, "vkCmdSetBlendConstants");
    g_pfn_vkCmdSetCullMode = (void*)GetProcAddress(h, "vkCmdSetCullMode");
    g_pfn_vkCmdSetDepthBias = (void*)GetProcAddress(h, "vkCmdSetDepthBias");
    g_pfn_vkCmdSetDepthBiasEnable = (void*)GetProcAddress(h, "vkCmdSetDepthBiasEnable");
    g_pfn_vkCmdSetDepthBounds = (void*)GetProcAddress(h, "vkCmdSetDepthBounds");
    g_pfn_vkCmdSetDepthBoundsTestEnable = (void*)GetProcAddress(h, "vkCmdSetDepthBoundsTestEnable");
    g_pfn_vkCmdSetDepthCompareOp = (void*)GetProcAddress(h, "vkCmdSetDepthCompareOp");
    g_pfn_vkCmdSetDepthTestEnable = (void*)GetProcAddress(h, "vkCmdSetDepthTestEnable");
    g_pfn_vkCmdSetDepthWriteEnable = (void*)GetProcAddress(h, "vkCmdSetDepthWriteEnable");
    g_pfn_vkCmdSetDeviceMask = (void*)GetProcAddress(h, "vkCmdSetDeviceMask");
    g_pfn_vkCmdSetEvent = (void*)GetProcAddress(h, "vkCmdSetEvent");
    g_pfn_vkCmdSetEvent2 = (void*)GetProcAddress(h, "vkCmdSetEvent2");
    g_pfn_vkCmdSetFrontFace = (void*)GetProcAddress(h, "vkCmdSetFrontFace");
    g_pfn_vkCmdSetLineWidth = (void*)GetProcAddress(h, "vkCmdSetLineWidth");
    g_pfn_vkCmdSetPrimitiveRestartEnable = (void*)GetProcAddress(h, "vkCmdSetPrimitiveRestartEnable");
    g_pfn_vkCmdSetPrimitiveTopology = (void*)GetProcAddress(h, "vkCmdSetPrimitiveTopology");
    g_pfn_vkCmdSetRasterizerDiscardEnable = (void*)GetProcAddress(h, "vkCmdSetRasterizerDiscardEnable");
    g_pfn_vkCmdSetScissor = (void*)GetProcAddress(h, "vkCmdSetScissor");
    g_pfn_vkCmdSetScissorWithCount = (void*)GetProcAddress(h, "vkCmdSetScissorWithCount");
    g_pfn_vkCmdSetStencilCompareMask = (void*)GetProcAddress(h, "vkCmdSetStencilCompareMask");
    g_pfn_vkCmdSetStencilOp = (void*)GetProcAddress(h, "vkCmdSetStencilOp");
    g_pfn_vkCmdSetStencilReference = (void*)GetProcAddress(h, "vkCmdSetStencilReference");
    g_pfn_vkCmdSetStencilTestEnable = (void*)GetProcAddress(h, "vkCmdSetStencilTestEnable");
    g_pfn_vkCmdSetStencilWriteMask = (void*)GetProcAddress(h, "vkCmdSetStencilWriteMask");
    g_pfn_vkCmdSetViewport = (void*)GetProcAddress(h, "vkCmdSetViewport");
    g_pfn_vkCmdSetViewportWithCount = (void*)GetProcAddress(h, "vkCmdSetViewportWithCount");
    g_pfn_vkCmdUpdateBuffer = (void*)GetProcAddress(h, "vkCmdUpdateBuffer");
    g_pfn_vkCmdWaitEvents = (void*)GetProcAddress(h, "vkCmdWaitEvents");
    g_pfn_vkCmdWaitEvents2 = (void*)GetProcAddress(h, "vkCmdWaitEvents2");
    g_pfn_vkCmdWriteTimestamp = (void*)GetProcAddress(h, "vkCmdWriteTimestamp");
    g_pfn_vkCmdWriteTimestamp2 = (void*)GetProcAddress(h, "vkCmdWriteTimestamp2");
    g_pfn_vkCreateBuffer = (void*)GetProcAddress(h, "vkCreateBuffer");
    g_pfn_vkCreateBufferView = (void*)GetProcAddress(h, "vkCreateBufferView");
    g_pfn_vkCreateCommandPool = (void*)GetProcAddress(h, "vkCreateCommandPool");
    g_pfn_vkCreateComputePipelines = (void*)GetProcAddress(h, "vkCreateComputePipelines");
    g_pfn_vkCreateDescriptorPool = (void*)GetProcAddress(h, "vkCreateDescriptorPool");
    g_pfn_vkCreateDescriptorSetLayout = (void*)GetProcAddress(h, "vkCreateDescriptorSetLayout");
    g_pfn_vkCreateDescriptorUpdateTemplate = (void*)GetProcAddress(h, "vkCreateDescriptorUpdateTemplate");
    g_pfn_vkCreateDevice = (void*)GetProcAddress(h, "vkCreateDevice");
    g_pfn_vkCreateEvent = (void*)GetProcAddress(h, "vkCreateEvent");
    g_pfn_vkCreateFence = (void*)GetProcAddress(h, "vkCreateFence");
    g_pfn_vkCreateFramebuffer = (void*)GetProcAddress(h, "vkCreateFramebuffer");
    g_pfn_vkCreateGraphicsPipelines = (void*)GetProcAddress(h, "vkCreateGraphicsPipelines");
    g_pfn_vkCreateImage = (void*)GetProcAddress(h, "vkCreateImage");
    g_pfn_vkCreateImageView = (void*)GetProcAddress(h, "vkCreateImageView");
    g_pfn_vkCreateInstance = (void*)GetProcAddress(h, "vkCreateInstance");
    g_pfn_vkCreatePipelineCache = (void*)GetProcAddress(h, "vkCreatePipelineCache");
    g_pfn_vkCreatePipelineLayout = (void*)GetProcAddress(h, "vkCreatePipelineLayout");
    g_pfn_vkCreatePrivateDataSlot = (void*)GetProcAddress(h, "vkCreatePrivateDataSlot");
    g_pfn_vkCreateQueryPool = (void*)GetProcAddress(h, "vkCreateQueryPool");
    g_pfn_vkCreateRenderPass = (void*)GetProcAddress(h, "vkCreateRenderPass");
    g_pfn_vkCreateRenderPass2 = (void*)GetProcAddress(h, "vkCreateRenderPass2");
    g_pfn_vkCreateSampler = (void*)GetProcAddress(h, "vkCreateSampler");
    g_pfn_vkCreateSamplerYcbcrConversion = (void*)GetProcAddress(h, "vkCreateSamplerYcbcrConversion");
    g_pfn_vkCreateSemaphore = (void*)GetProcAddress(h, "vkCreateSemaphore");
    g_pfn_vkCreateShaderModule = (void*)GetProcAddress(h, "vkCreateShaderModule");
    g_pfn_vkCreateSwapchainKHR = (void*)GetProcAddress(h, "vkCreateSwapchainKHR");
    g_pfn_vkCreateWin32SurfaceKHR = (void*)GetProcAddress(h, "vkCreateWin32SurfaceKHR");
    g_pfn_vkDestroyBuffer = (void*)GetProcAddress(h, "vkDestroyBuffer");
    g_pfn_vkDestroyBufferView = (void*)GetProcAddress(h, "vkDestroyBufferView");
    g_pfn_vkDestroyCommandPool = (void*)GetProcAddress(h, "vkDestroyCommandPool");
    g_pfn_vkDestroyDescriptorPool = (void*)GetProcAddress(h, "vkDestroyDescriptorPool");
    g_pfn_vkDestroyDescriptorSetLayout = (void*)GetProcAddress(h, "vkDestroyDescriptorSetLayout");
    g_pfn_vkDestroyDescriptorUpdateTemplate = (void*)GetProcAddress(h, "vkDestroyDescriptorUpdateTemplate");
    g_pfn_vkDestroyDevice = (void*)GetProcAddress(h, "vkDestroyDevice");
    g_pfn_vkDestroyEvent = (void*)GetProcAddress(h, "vkDestroyEvent");
    g_pfn_vkDestroyFence = (void*)GetProcAddress(h, "vkDestroyFence");
    g_pfn_vkDestroyFramebuffer = (void*)GetProcAddress(h, "vkDestroyFramebuffer");
    g_pfn_vkDestroyImage = (void*)GetProcAddress(h, "vkDestroyImage");
    g_pfn_vkDestroyImageView = (void*)GetProcAddress(h, "vkDestroyImageView");
    g_pfn_vkDestroyInstance = (void*)GetProcAddress(h, "vkDestroyInstance");
    g_pfn_vkDestroyPipeline = (void*)GetProcAddress(h, "vkDestroyPipeline");
    g_pfn_vkDestroyPipelineCache = (void*)GetProcAddress(h, "vkDestroyPipelineCache");
    g_pfn_vkDestroyPipelineLayout = (void*)GetProcAddress(h, "vkDestroyPipelineLayout");
    g_pfn_vkDestroyPrivateDataSlot = (void*)GetProcAddress(h, "vkDestroyPrivateDataSlot");
    g_pfn_vkDestroyQueryPool = (void*)GetProcAddress(h, "vkDestroyQueryPool");
    g_pfn_vkDestroyRenderPass = (void*)GetProcAddress(h, "vkDestroyRenderPass");
    g_pfn_vkDestroySampler = (void*)GetProcAddress(h, "vkDestroySampler");
    g_pfn_vkDestroySamplerYcbcrConversion = (void*)GetProcAddress(h, "vkDestroySamplerYcbcrConversion");
    g_pfn_vkDestroySemaphore = (void*)GetProcAddress(h, "vkDestroySemaphore");
    g_pfn_vkDestroyShaderModule = (void*)GetProcAddress(h, "vkDestroyShaderModule");
    g_pfn_vkDestroySurfaceKHR = (void*)GetProcAddress(h, "vkDestroySurfaceKHR");
    g_pfn_vkDestroySwapchainKHR = (void*)GetProcAddress(h, "vkDestroySwapchainKHR");
    g_pfn_vkDeviceWaitIdle = (void*)GetProcAddress(h, "vkDeviceWaitIdle");
    g_pfn_vkEndCommandBuffer = (void*)GetProcAddress(h, "vkEndCommandBuffer");
    g_pfn_vkEnumerateDeviceExtensionProperties = (void*)GetProcAddress(h, "vkEnumerateDeviceExtensionProperties");
    g_pfn_vkEnumerateDeviceLayerProperties = (void*)GetProcAddress(h, "vkEnumerateDeviceLayerProperties");
    g_pfn_vkEnumerateInstanceExtensionProperties = (void*)GetProcAddress(h, "vkEnumerateInstanceExtensionProperties");
    g_pfn_vkEnumerateInstanceLayerProperties = (void*)GetProcAddress(h, "vkEnumerateInstanceLayerProperties");
    g_pfn_vkEnumerateInstanceVersion = (void*)GetProcAddress(h, "vkEnumerateInstanceVersion");
    g_pfn_vkEnumeratePhysicalDeviceGroups = (void*)GetProcAddress(h, "vkEnumeratePhysicalDeviceGroups");
    g_pfn_vkEnumeratePhysicalDevices = (void*)GetProcAddress(h, "vkEnumeratePhysicalDevices");
    g_pfn_vkFlushMappedMemoryRanges = (void*)GetProcAddress(h, "vkFlushMappedMemoryRanges");
    g_pfn_vkFreeCommandBuffers = (void*)GetProcAddress(h, "vkFreeCommandBuffers");
    g_pfn_vkFreeDescriptorSets = (void*)GetProcAddress(h, "vkFreeDescriptorSets");
    g_pfn_vkFreeMemory = (void*)GetProcAddress(h, "vkFreeMemory");
    g_pfn_vkGetBufferDeviceAddress = (void*)GetProcAddress(h, "vkGetBufferDeviceAddress");
    g_pfn_vkGetBufferMemoryRequirements = (void*)GetProcAddress(h, "vkGetBufferMemoryRequirements");
    g_pfn_vkGetBufferMemoryRequirements2 = (void*)GetProcAddress(h, "vkGetBufferMemoryRequirements2");
    g_pfn_vkGetBufferOpaqueCaptureAddress = (void*)GetProcAddress(h, "vkGetBufferOpaqueCaptureAddress");
    g_pfn_vkGetDescriptorSetLayoutSupport = (void*)GetProcAddress(h, "vkGetDescriptorSetLayoutSupport");
    g_pfn_vkGetDeviceBufferMemoryRequirements = (void*)GetProcAddress(h, "vkGetDeviceBufferMemoryRequirements");
    g_pfn_vkGetDeviceGroupPeerMemoryFeatures = (void*)GetProcAddress(h, "vkGetDeviceGroupPeerMemoryFeatures");
    g_pfn_vkGetDeviceImageMemoryRequirements = (void*)GetProcAddress(h, "vkGetDeviceImageMemoryRequirements");
    g_pfn_vkGetDeviceImageSparseMemoryRequirements = (void*)GetProcAddress(h, "vkGetDeviceImageSparseMemoryRequirements");
    g_pfn_vkGetDeviceMemoryCommitment = (void*)GetProcAddress(h, "vkGetDeviceMemoryCommitment");
    g_pfn_vkGetDeviceMemoryOpaqueCaptureAddress = (void*)GetProcAddress(h, "vkGetDeviceMemoryOpaqueCaptureAddress");
    g_pfn_vkGetDeviceProcAddr = (void*)GetProcAddress(h, "vkGetDeviceProcAddr");
    g_pfn_vkGetDeviceQueue = (void*)GetProcAddress(h, "vkGetDeviceQueue");
    g_pfn_vkGetDeviceQueue2 = (void*)GetProcAddress(h, "vkGetDeviceQueue2");
    g_pfn_vkGetEventStatus = (void*)GetProcAddress(h, "vkGetEventStatus");
    g_pfn_vkGetFenceStatus = (void*)GetProcAddress(h, "vkGetFenceStatus");
    g_pfn_vkGetImageMemoryRequirements = (void*)GetProcAddress(h, "vkGetImageMemoryRequirements");
    g_pfn_vkGetImageMemoryRequirements2 = (void*)GetProcAddress(h, "vkGetImageMemoryRequirements2");
    g_pfn_vkGetImageMemoryRequirements2KHR = (void*)GetProcAddress(h, "vkGetImageMemoryRequirements2KHR");
    g_pfn_vkGetImageSparseMemoryRequirements = (void*)GetProcAddress(h, "vkGetImageSparseMemoryRequirements");
    g_pfn_vkGetImageSparseMemoryRequirements2 = (void*)GetProcAddress(h, "vkGetImageSparseMemoryRequirements2");
    g_pfn_vkGetImageSubresourceLayout = (void*)GetProcAddress(h, "vkGetImageSubresourceLayout");
    g_pfn_vkGetInstanceProcAddr = (void*)GetProcAddress(h, "vkGetInstanceProcAddr");
    g_pfn_vkGetPhysicalDeviceExternalBufferProperties = (void*)GetProcAddress(h, "vkGetPhysicalDeviceExternalBufferProperties");
    g_pfn_vkGetPhysicalDeviceExternalFenceProperties = (void*)GetProcAddress(h, "vkGetPhysicalDeviceExternalFenceProperties");
    g_pfn_vkGetPhysicalDeviceExternalSemaphoreProperties = (void*)GetProcAddress(h, "vkGetPhysicalDeviceExternalSemaphoreProperties");
    g_pfn_vkGetPhysicalDeviceFeatures = (void*)GetProcAddress(h, "vkGetPhysicalDeviceFeatures");
    g_pfn_vkGetPhysicalDeviceFeatures2 = (void*)GetProcAddress(h, "vkGetPhysicalDeviceFeatures2");
    g_pfn_vkGetPhysicalDeviceFeatures2KHR = (void*)GetProcAddress(h, "vkGetPhysicalDeviceFeatures2KHR");
    g_pfn_vkGetPhysicalDeviceFormatProperties = (void*)GetProcAddress(h, "vkGetPhysicalDeviceFormatProperties");
    g_pfn_vkGetPhysicalDeviceFormatProperties2 = (void*)GetProcAddress(h, "vkGetPhysicalDeviceFormatProperties2");
    g_pfn_vkGetPhysicalDeviceImageFormatProperties = (void*)GetProcAddress(h, "vkGetPhysicalDeviceImageFormatProperties");
    g_pfn_vkGetPhysicalDeviceImageFormatProperties2 = (void*)GetProcAddress(h, "vkGetPhysicalDeviceImageFormatProperties2");
    g_pfn_vkGetPhysicalDeviceMemoryProperties = (void*)GetProcAddress(h, "vkGetPhysicalDeviceMemoryProperties");
    g_pfn_vkGetPhysicalDeviceMemoryProperties2 = (void*)GetProcAddress(h, "vkGetPhysicalDeviceMemoryProperties2");
    g_pfn_vkGetPhysicalDeviceProperties = (void*)GetProcAddress(h, "vkGetPhysicalDeviceProperties");
    g_pfn_vkGetPhysicalDeviceProperties2 = (void*)GetProcAddress(h, "vkGetPhysicalDeviceProperties2");
    g_pfn_vkGetPhysicalDeviceProperties2KHR = (void*)GetProcAddress(h, "vkGetPhysicalDeviceProperties2KHR");
    g_pfn_vkGetPhysicalDeviceQueueFamilyProperties = (void*)GetProcAddress(h, "vkGetPhysicalDeviceQueueFamilyProperties");
    g_pfn_vkGetPhysicalDeviceQueueFamilyProperties2 = (void*)GetProcAddress(h, "vkGetPhysicalDeviceQueueFamilyProperties2");
    g_pfn_vkGetPhysicalDeviceSparseImageFormatProperties = (void*)GetProcAddress(h, "vkGetPhysicalDeviceSparseImageFormatProperties");
    g_pfn_vkGetPhysicalDeviceSparseImageFormatProperties2 = (void*)GetProcAddress(h, "vkGetPhysicalDeviceSparseImageFormatProperties2");
    g_pfn_vkGetPhysicalDeviceSurfaceCapabilitiesKHR = (void*)GetProcAddress(h, "vkGetPhysicalDeviceSurfaceCapabilitiesKHR");
    g_pfn_vkGetPhysicalDeviceSurfaceFormatsKHR = (void*)GetProcAddress(h, "vkGetPhysicalDeviceSurfaceFormatsKHR");
    g_pfn_vkGetPhysicalDeviceSurfacePresentModesKHR = (void*)GetProcAddress(h, "vkGetPhysicalDeviceSurfacePresentModesKHR");
    g_pfn_vkGetPhysicalDeviceSurfaceSupportKHR = (void*)GetProcAddress(h, "vkGetPhysicalDeviceSurfaceSupportKHR");
    g_pfn_vkGetPhysicalDeviceToolProperties = (void*)GetProcAddress(h, "vkGetPhysicalDeviceToolProperties");
    g_pfn_vkGetPipelineCacheData = (void*)GetProcAddress(h, "vkGetPipelineCacheData");
    g_pfn_vkGetPrivateData = (void*)GetProcAddress(h, "vkGetPrivateData");
    g_pfn_vkGetQueryPoolResults = (void*)GetProcAddress(h, "vkGetQueryPoolResults");
    g_pfn_vkGetRenderAreaGranularity = (void*)GetProcAddress(h, "vkGetRenderAreaGranularity");
    g_pfn_vkGetSemaphoreCounterValue = (void*)GetProcAddress(h, "vkGetSemaphoreCounterValue");
    g_pfn_vkGetSwapchainImagesKHR = (void*)GetProcAddress(h, "vkGetSwapchainImagesKHR");
    g_pfn_vkInvalidateMappedMemoryRanges = (void*)GetProcAddress(h, "vkInvalidateMappedMemoryRanges");
    g_pfn_vkMapMemory = (void*)GetProcAddress(h, "vkMapMemory");
    g_pfn_vkMergePipelineCaches = (void*)GetProcAddress(h, "vkMergePipelineCaches");
    g_pfn_vkQueueBindSparse = (void*)GetProcAddress(h, "vkQueueBindSparse");
    g_pfn_vkQueuePresentKHR = (void*)GetProcAddress(h, "vkQueuePresentKHR");
    g_pfn_vkQueueSubmit = (void*)GetProcAddress(h, "vkQueueSubmit");
    g_pfn_vkQueueSubmit2 = (void*)GetProcAddress(h, "vkQueueSubmit2");
    g_pfn_vkQueueWaitIdle = (void*)GetProcAddress(h, "vkQueueWaitIdle");
    g_pfn_vkResetCommandBuffer = (void*)GetProcAddress(h, "vkResetCommandBuffer");
    g_pfn_vkResetCommandPool = (void*)GetProcAddress(h, "vkResetCommandPool");
    g_pfn_vkResetDescriptorPool = (void*)GetProcAddress(h, "vkResetDescriptorPool");
    g_pfn_vkResetEvent = (void*)GetProcAddress(h, "vkResetEvent");
    g_pfn_vkResetFences = (void*)GetProcAddress(h, "vkResetFences");
    g_pfn_vkResetQueryPool = (void*)GetProcAddress(h, "vkResetQueryPool");
    g_pfn_vkSetEvent = (void*)GetProcAddress(h, "vkSetEvent");
    g_pfn_vkSetPrivateData = (void*)GetProcAddress(h, "vkSetPrivateData");
    g_pfn_vkSignalSemaphore = (void*)GetProcAddress(h, "vkSignalSemaphore");
    g_pfn_vkTrimCommandPool = (void*)GetProcAddress(h, "vkTrimCommandPool");
    g_pfn_vkUnmapMemory = (void*)GetProcAddress(h, "vkUnmapMemory");
    g_pfn_vkUpdateDescriptorSetWithTemplate = (void*)GetProcAddress(h, "vkUpdateDescriptorSetWithTemplate");
    g_pfn_vkUpdateDescriptorSets = (void*)GetProcAddress(h, "vkUpdateDescriptorSets");
    g_pfn_vkWaitForFences = (void*)GetProcAddress(h, "vkWaitForFences");
    g_pfn_vkWaitSemaphores = (void*)GetProcAddress(h, "vkWaitSemaphores");
}

